homeassistant:
  url: "http://homeassistant.local:8123"
  token: "your_long_lived_access_token_here"
  # Optional: specify device name (defaults to hostname if not set)
  # device_name: "my-computer"
